name: minitoken-besu-ethereum

on:
  push:
    branches: [ main ]
    paths:
      - 'contracts/minitoken/solidity/**'
      - 'samples/minitoken-besu-ethereum/**'
      - '.github/workflows/minitoken-besu-ethereum.yml'
  pull_request:
    paths:
      - 'contracts/minitoken/solidity/**'
      - 'samples/minitoken-besu-ethereum/**'
      - '.github/workflows/minitoken-besu-ethereum.yml'

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./samples/minitoken-besu-ethereum
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.16
        uses: actions/setup-go@v3
        with:
          go-version: 1.16
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Download NPM dependency for samples
        run: npm ci
      - name: Download NPM dependency for contracts
        run: npm ci
        working-directory: ./contracts/minitoken/solidity
      - name: Setup
        run: make setup
      - name: Run E2E
        run: make e2e
